#!/usr/bin/env bash
# ----------------------------------------------------------------------
# run_vivado_impl.sh — Implementation (opt/place/route) & bitstream
#
# Usage:
#   ./scripts/run_vivado_impl.sh
#   TOP=core PART=xc7a100tcsg324-1 XDC=constraints/nexys_a7.xdc ./scripts/run_vivado_impl.sh
#
# Env overrides (optional):
#   TOP   : top module name (default: core)
#   RTL   : RTL directory (default: rtl) — used only if no synth DCP exists
#   OUT   : output dir for impl artifacts (default: build/impl)
#   SYNTH : path to synth dir or DCP (default: build/synth/core_synth.dcp)
#   PART  : FPGA part (default: xc7a100tcsg324-1)
#   XDC   : constraints file (default: constraints/nexys_a7.xdc if present)
#   BIT   : bitstream output name (default: ${TOP}.bit)
# ----------------------------------------------------------------------

set -euo pipefail

# Defaults
TOP="${TOP:-core}"
RTL="${RTL:-rtl}"
OUT="${OUT:-build/impl}"
PART="${PART:-xc7a100tcsg324-1}"
SYNTH_DEFAULT="build/synth/${TOP}_synth.dcp"
SYNTH="${SYNTH:-$SYNTH_DEFAULT}"
XDC="${XDC:-constraints/nexys_a7.xdc}"
[[ -f "$XDC" ]] || XDC=""
BIT="${BIT:-${TOP}.bit}"

mkdir -p "$OUT"

TCL="$OUT/impl.tcl"
LOG="$OUT/impl.log"

cat > "$TCL" <<'TCL'
# Auto-generated by run_vivado_impl.sh
proc msg {s} { puts "==> $s" }

set TOP   [getenv TOP]
set RTL   [getenv RTL]
set OUT   [getenv OUT]
set PART  [getenv PART]
set XDC   [getenv XDC]
set SYNTH [getenv SYNTH]
set BIT   [getenv BIT]

file mkdir $OUT
create_project -in_memory -part $PART

# Prefer starting from synthesis checkpoint if available; else read sources.
if {[file exists $SYNTH]} {
  msg "Opening synth checkpoint: $SYNTH"
  open_checkpoint $SYNTH
} else {
  msg "No synth checkpoint found. Falling back to reading RTL from $RTL"
  set rtl_files [glob -nocomplain -directory $RTL *.v]
  if {[llength $rtl_files] == 0} { error "No Verilog files found in $RTL" }
  add_files -fileset sources_1 $rtl_files
  if {[file exists "$RTL/defines.vh"]} {
    set_property include_dirs "$RTL" [current_fileset]
  }
  if {$XDC ne "" && [file exists $XDC]} {
    add_files -fileset constrs_1 $XDC
  }
  read_verilog $rtl_files
  synth_design -top $TOP -part $PART -directive default
}

# Ensure constraints are present (ok if already loaded via DCP)
if {$XDC ne "" && [file exists $XDC]} {
  msg "Adding constraints: $XDC"
  add_files -fileset constrs_1 $XDC
} else {
  msg "No external constraints provided (XDC empty or missing)"
}

# Implementation flow
msg "opt_design"
opt_design

msg "place_design"
place_design

msg "phys_opt_design (post-place)"
phys_opt_design

msg "route_design"
route_design

msg "phys_opt_design (post-route)"
phys_opt_design -directive Explore

# Reports
report_utilization     -file $OUT/utilization_impl.rpt   -hierarchical -pb $OUT/utilization_impl.pb
report_timing_summary  -file $OUT/timing_impl.rpt
report_drc             -file $OUT/drc_impl.rpt
report_power           -file $OUT/power_impl.rpt

# Outputs
write_checkpoint -force $OUT/${TOP}_impl.dcp
write_bitstream  -force $OUT/$BIT

msg "Implementation complete. Bitstream: $OUT/$BIT"
exit
TCL

echo "==> Running Vivado implementation (see $LOG)"
vivado -mode batch -source "$TCL" -nojournal -log "$LOG" || {
  echo "Vivado implementation failed. Check $LOG"
  exit 1
}

echo "==> Done."
echo "    - $OUT/${TOP}_impl.dcp"
echo "    - $OUT/$BIT"
echo "    - $OUT/timing_impl.rpt, $OUT/utilization_impl.rpt, $OUT/power_impl.rpt, $OUT/drc_impl.rpt"
