#!/usr/bin/env bash
# ----------------------------------------------------------------------
# run_vivado_synth.sh  —  Batch synthesis for the RISC-V core in Vivado
#
# Usage:
#   ./scripts/run_vivado_synth.sh
#   TOP=core PART=xc7a100tcsg324-1 XDC=constraints/nexys_a7.xdc ./scripts/run_vivado_synth.sh
#
# Env overrides (all optional):
#   TOP   : top module name (default: core)
#   RTL   : RTL directory (default: rtl)
#   TB    : testbench dir (ignored for synth, default: tb)
#   XDC   : path to XDC constraints file (default: constraints/nexys_a7.xdc if exists)
#   PART  : FPGA part (default: xc7a100tcsg324-1  # Digilent Nexys A7-100T)
#   OUT   : build/output dir (default: build/synth)
# ----------------------------------------------------------------------

set -euo pipefail

# ---- Defaults ----
TOP="${TOP:-core}"
RTL="${RTL:-rtl}"
TB="${TB:-tb}"
OUT="${OUT:-build/synth}"
PART="${PART:-xc7a100tcsg324-1}"

# Try a sensible default XDC if present; otherwise empty (constraints optional for synth)
XDC="${XDC:-constraints/nexys_a7.xdc}"
[[ -f "$XDC" ]] || XDC=""

mkdir -p "$OUT"

TCL="$OUT/synth.tcl"
LOG="$OUT/synth.log"

# ---- Generate TCL ----
cat > "$TCL" <<'TCL'
# Auto-generated by run_vivado_synth.sh
proc msg {s} { puts "==> $s" }

# Params come from environment (Vivado passes current env into -mode batch)
set TOP   [getenv TOP]
set RTL   [getenv RTL]
set TB    [getenv TB]
set OUT   [getenv OUT]
set PART  [getenv PART]
set XDC   [getenv XDC]

file mkdir $OUT

msg "Creating in-memory project for $PART"
create_project -in_memory -part $PART

# Add RTL sources
msg "Adding RTL sources from $RTL"
set rtl_files [glob -nocomplain -directory $RTL *.v]
if {[llength $rtl_files] == 0} {
  error "No Verilog files found in $RTL"
}
add_files -fileset sources_1 $rtl_files

# Add optional headers and SystemVerilog if you have them
if {[file exists "$RTL/defines.vh"]} {
  set_property include_dirs "$RTL" [current_fileset]
}

# XDC constraints if provided
if {$XDC ne "" && [file exists $XDC]} {
  msg "Adding constraints: $XDC"
  add_files -fileset constrs_1 $XDC
} else {
  msg "No XDC provided; proceeding without constraints"
}

# Set top module
msg "Setting top: $TOP"
set_property top $TOP [current_fileset]

# Read, elaborate, and synthesize
msg "Launching synthesis..."
read_verilog $rtl_files
synth_design -top $TOP -part $PART -directive default

# Write checkpoints & netlists
write_checkpoint -force $OUT/${TOP}_synth.dcp
write_edif      -force $OUT/${TOP}_synth.edf
write_verilog   -force -mode synth_stub $OUT/${TOP}_synth_stub.v

# Reports
report_utilization   -file $OUT/utilization_synth.rpt   -hierarchical -pb $OUT/utilization_synth.pb
report_timing_summary -file $OUT/timing_synth.rpt
report_clock_networks -file $OUT/clock_networks.rpt

msg "Synthesis complete. Outputs in $OUT"
exit
TCL

# ---- Run Vivado in batch ----
echo "==> Running Vivado synthesis (see $LOG)"
vivado -mode batch -source "$TCL" -nojournal -log "$LOG" || {
  echo "Vivado synthesis failed. Check $LOG"
  exit 1
}

echo "==> Done. Artifacts written to: $OUT"
echo "    - ${OUT}/${TOP}_synth.dcp (checkpoint)"
echo "    - ${OUT}/${TOP}_synth.edf (netlist)"
echo "    - ${OUT}/utilization_synth.rpt, timing_synth.rpt, clock_networks.rpt"
